### ISSUE TITLE
unable to recieve feedback from certain commands after using vanish mod.

### ISSUE THREAD

**Issue by creaper33** [RedstoneDubstep/Vanishmod#23]
I don't see any errors in the console, but after using /vanish (even if you're not vanished), certain commands will not show in chat.

For example, if I do /vanish, then type /forge tps I don't see anything in chat when it should tell me the tps. Even if I unvanish it still will not show in chat. It seems to have stuffed my player up and I have not found a fix.

**Comment by creaper33** [comment]
btw I'm using the 1.20.1 version

**Comment by RedstoneDubstep** [comment]
Hello,
I cannot reproduce this with Vanishmod 1.1.14 (Forge 47.1.1) on Minecraft 1.20.1. Are you using any other mods that might interfere with this behavior?

https://github.com/RedstoneDubstep/Vanishmod/assets/42962686/c7a0cd59-d4f9-47e9-821a-334a4be6677f

**Comment by creaper33** [comment]
I'm using ATM9 0.2.27 with these extra mods:
![image](https://github.com/RedstoneDubstep/Vanishmod/assets/147256938/350bac12-e438-4d72-af5d-5050fd3d3af0)

Here is a video of the bug:

https://github.com/RedstoneDubstep/Vanishmod/assets/147256938/a23224a4-67dd-47ae-ad90-5ec2f2cead4c

There are many mods in this server, I don't know what one could be interfering with vanish.

I'll give you the debug.log so you can see if you can find anything noteworthy in it. I join the server at [10Dec2023 10:20:01.253].
https://drive.google.com/file/d/1Rn2fg5JyXPf8L9i4XIeb9N_GijDLiUCC/view?usp=sharing

**Comment by creaper33** [comment]
The commands still execute though, they just don't show.

**Comment by RedstoneDubstep** [comment]
Unfortunately I cannot find anything suspicious in the debug log. Since the commands still get executed (and since this only seems to apply to some commands, since spark still seems to work in your video), it's only a minor issue, so I won't try to pin it down to one of 400+ mods from the ATM pack. I'll leave this issue open in case someone can reproduce it with a smaller set of mods, in which case I might investigate further. Thanks for reporting though!
