### ISSUE TITLE
[Feature Request] Localization Support

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [RedstoneDubstep/Vanishmod#24]
Hello!
I think it's nice-to-have Localization Support Feature for this Mod, so Players that speak other Languages can easily use this Mod.

**Comment by RedstoneDubstep** [comment]
Hello,
this is unfortunately not possible due to the client not being aware of any translations of this mod, because this mod is intended to only be installed on the server side. So the server would only be able to send the raw translation keys (because it has no idea which language the client is playing in), and the client wouldn't know how to translate the keys because the actual translation strings would only exist on the server (and not be sent over the network).

**Comment by SrRapero720** [comment]
you can get the translation string and send a TextComponent (`Component.literal()`).
is not fancy in code but works pretty well
