### ISSUE TITLE
Minecolonies chat message 

### ISSUE THREAD

**Issue by bomber1992** [RedstoneDubstep/Vanishmod#35]
Is it possible to add to the mod that when you walk into a mine colony the owner does not get the message that someone has entered the colony? Because unfortunately you are not protected from this in Vanish and are therefore recognizable

**Comment by RedstoneDubstep** [comment]
Hello, unfortunately issues like these are hard to fix from my side, since I'd need to mixin (= code-inject) into MineColonies to prevent them from showing messages mentioning vanished players, and doing this for other mods is generally considered unfavourable and brittle. The only thing you could try through Vanishmod is turning the `fixPlayerDetectionModCompatibility` config on, though that may have unintended side effects (as outlined in the config's description). 
The best way to fix issues like these is to ask the MineColonies devs to include a check for whether a player is vanished before sending these messages, either by directly calling the Vanishmod method `VanishUtil#isVanished` or indirectly through e.g. `LivingEntity#canBeSeenByAnyone`, which Vanishmod automatically injects into.
