### ISSUE TITLE
isVanished() is always false

### ISSUE THREAD

**Issue by NepNep21** [RedstoneDubstep/Vanishmod#6]
Currently helping someone else having an issue with this mod on 1.16.4, i have confirmed it does exist for me as well, the issue is that VanishUtil.isVanished() always returns false, after a bit of testing it seems to be caused by "player.getPersistentData().getCompound(PlayerEntity.PERSISTED_NBT_TAG)" being empty, even after running /vanish, i do not know enough to fix this myself

**Comment by RedstoneDubstep** [comment]
Hello,
I just tested it myself and you were right, the code I use to save the vanished status into NBT doesn't work if there isn't already a NBT at the location (which there was in my testing world, so I didn't notice). Thanks for reporting, the bug will be fixed in the next version of the mod (v1.0.9).
