### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by ANONYMOUS6010** [RedstoneDubstep/Vanishmod#8]
When this mod is used on the server it just stalls and doesn't load. It doesn't crash it just does not load at all.

**Comment by RedstoneDubstep** [comment]
Thanks for the info, could you please tell me what Minecraft version/Vanishmod version/Forge version/other mods you're using? And the log until the server stops loading could maybe be useful

**Comment by ANONYMOUS6010** [comment]
I am using the most recent one for 1.16.5: 1.16.5-1.1.2.1.jar. 
the mods I am using cn be found here: https://drive.google.com/drive/folders/1ZEYhX6S5XRd-Y0joOwg79vSf3HkYLMDS?usp=sharing

**Comment by RedstoneDubstep** [comment]
Tried Vanishmod 1.1.2.1 with Forge version 36.2.28 and the server started up fine. So I'm assuming it's a mod conflict, and thus it would be very helpful if you paste the log that gets printed until the server stops loading (because of a potential warning in there mentioning the conflicting mods), e.g. via pastebin or a similar site.

**Comment by ANONYMOUS6010** [comment]
We use forge version 36.2.20. Not sure if that is the problem, and I will paste the log as soon as I can

**Comment by ANONYMOUS6010** [comment]
So I tried the new updated version for 1.16.5, the 1.1.3, and the server console says the server is started, yet when I try to log on, it is not on. We also got this error. (Sorry I have not responded at all, I had some serious shit and had no time, my apologies.)
![Vasek](https://user-images.githubusercontent.com/99668958/156470897-3a4c5408-49bd-4a41-82c0-660d1f45193e.png)

**Comment by RedstoneDubstep** [comment]
That `Missing data pack` message usually only appears if a previously installed mod is removed from the server, which shouldn't be a problem for the Vanishmod, as it doesn't add blocks/items/etc.
I tried to start a 1.16.5 Forge Server (36.2.29) yesterday with Vanishmod v1.1.3 installed, and I was able to join that server with a Forge client without any problems/unusual log messages/etc. So I would, again, be interested in the the full log that gets printed when the server starts/when someone tries (and fails) to join.
And if you have other mods installed, could you please try to start the server with only Vanishmod installed? That way we can figure out more easily if this error originates from a mod conflict.

**Comment by ANONYMOUS6010** [comment]
https://pastebin.com/XtDy5uS3
That one is the server console
And this one is the crash log
https://pastebin.com/XgrWqN9A

I did try vanish by itself and it did load properly.

**Comment by RedstoneDubstep** [comment]
Thank you for your feedback! I (hopefully) was able to figure out and solve the issue with the help of the logs you gave me, it would be very helpful if you could try the attached mod file (where the issue should be fixed in) and report back if it works for you.
[Vanishmod-1.16.5-1.1.3.1.zip](https://github.com/RedstoneDubstep/Vanishmod/files/8193120/Vanishmod-1.16.5-1.1.3.1.zip)

**Comment by ANONYMOUS6010** [comment]
Its works now! Thanks so much! (A question: Is there a way to tell if you are vanished?, and a suggestion: Could you add so when you hit tab, it says whether you are vanished or not?)
Hope you have a nice day

**Comment by RedstoneDubstep** [comment]
Nice to hear that it works! Regarding your question, yes, there is a way to tell if you're vanished: the command `/vanish get <player>` should tell you in the chat whether you/a player is vanished or not. I'll look into implementing the tab feature.
